---
title: "data analysis"
author: "Joshua Berry"
date: "12/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(GGally)
library(knitr)
library(gtsummary)
library(gt)
library(rstatix)
```

## R Markdown

```{r}
results <- read.csv("results.csv")

numeric_results <- read_csv("numeric_results_3.csv",
                          col_types = cols(Q36 = col_number(),
                          Q35 = col_number(),
                          Q37 = col_number(),
                          Q40 = col_number(),
                          Q41 = col_number(),
                          Q43 = col_number(),
                          Q45_1 = col_number(),
                          Q47_1  = col_number(),
                          Q49  = col_number(),
                          Q50 = col_number(),
                          Q51_1 = col_number(),
                          Q51_2  = col_number(),
                          Q51_3  = col_number(),
                          Q51_4 = col_number(),
                          Q51_5  = col_number(),
                          Q56_4  = col_number(),
                          Q2 = col_number(),
                          Q14  = col_number(),
                          Q16  = col_number(),
                          Q18 = col_number(),
                          Q19  = col_number(),
                          Q27  = col_number(),
                          Q26 = col_number(),
                          Q20  = col_number(),
                          condition = col_factor(),
                          Q54  = col_number())) %>%
  filter(condition %in% c("usabaseapp", "chinabaseapp",
                         "chinalovedapp", "chinahatedapp", 
                         "estoniabaseapp")) %>%
    rename(state = Q2, gender = Q14, age = Q16, race = Q18, asian_ethnicity = Q19,
         social_media = Q27, political_identification = Q20, education = Q26,
         income = Q54, time_spent_using_chinese_apps = Q43) %>%
  mutate(condition_scale = case_when(condition == "usabaseapp" ~ 1,
                                     condition == "chinabaseapp" ~ 2,
                                     condition == "chinahatedapp" ~ 3,
                                     condition == "chinalovedapp" ~ 4,
                                     condition == "estoniabaseapp" ~ 5,
                                     TRUE ~ NA_real_)) %>%
    mutate(political_identification = case_when(political_identification == 1 ~ "Democrat",
                                     political_identification == 2 ~ "Republican",
                                     political_identification == 3 ~ "Independent",
                                     political_identification == 4 ~ "Independent",
                                     TRUE ~ NA_character_)) %>%
    mutate(race = case_when(race == 1 ~ "White",
                                     race == 2 ~ "Black",
                                     race == 3 ~ "Other",
                                     race == 4 ~ "Asian",
                                     race == 5 ~ "Asian",
                                     race == 6 ~ "Other",
                                     TRUE ~ NA_character_)) %>%
      mutate(gender = case_when(gender == 1 ~ "Male",
                                     gender == 2 ~ "Female",
                                     TRUE ~ NA_character_)) %>%
    mutate(education = case_when(education == 1 ~ 0,
                                     education == 2 ~ 4,
                                     education == 3 ~ 6,
                                     education == 4 ~ 7,
                                     education == 5 ~ 10,
                                     education == 6 ~ 12,
                                     education == 7 ~ 17,
                                     education == 8 ~ 17,
                                     TRUE ~ NA_real_)) %>%
        mutate(Q51_1 = case_when(Q51_1 == 1 ~ 1,
                                     Q51_1 == 2 ~ 0,
                                     TRUE ~ NA_real_)) %>%
          mutate(Q51_2 = case_when(Q51_2 == 1 ~ 1,
                                     Q51_2 == 2 ~ 0,
                                     TRUE ~ NA_real_)) %>%
          mutate(Q51_3 = case_when(Q51_3 == 1 ~ 1,
                                     Q51_3 == 2 ~ 0,
                                     TRUE ~ NA_real_)) %>%
          mutate(Q51_4 = case_when(Q51_4 == 1 ~ 1,
                                     Q51_4 == 2 ~ 0,
                                     TRUE ~ NA_real_)) %>%
            mutate(Q51_5 = case_when(Q51_5 == 1 ~ 1,
                                     Q51_5 == 2 ~ 0,
                                     TRUE ~ NA_real_)) %>%
            mutate(time_spent_using_chinese_apps = case_when(time_spent_using_chinese_apps == 1 ~ 0,
                                     time_spent_using_chinese_apps == 2 ~ 1,
                                     time_spent_using_chinese_apps == 3 ~ 2,
                                     time_spent_using_chinese_apps == 4 ~ 4,
                                     time_spent_using_chinese_apps == 5 ~ 9,
                                     time_spent_using_chinese_apps == 6 ~ 15,
                                     TRUE ~ NA_real_))

numeric_results$condition <- relevel(numeric_results$condition, ref = "usabaseapp")

numeric_results$race<- factor(numeric_results$race, levels = c("Black", "Asian", "White", "Hispanic", "Other"))

mean(numeric_results$age, na.rm = TRUE)
  

```


```{r}
china.fav.lm <- lm(Q45_1 ~ gender + age + race + education 
                + political_identification + condition, data = numeric_results)

summary(china.fav.lm)

china.fav.tbl <-  tbl_regression(china.fav.lm, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Tbl. 1: Regression of Country-of-Origin Treatment Group Against Favorability Towards China", 
  subtitle = "Feeling Thermometer of 0 (Coldest) to 100 (Warmest)") %>%
    tab_source_note(md("Original MTurk Study, conducted 2020 Dec. 11-12 & 2021 Feb. 21,
                        n = 348"))


trust.lm <- lm(Q37 ~ gender + age + race + education 
                + political_identification + condition, data = numeric_results)

summary(trust.lm)

trust.tbl <-  tbl_regression(trust.lm, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Tbl. 2: Regression of Treatment Group Against Assigned Trust towards App Company", 
  subtitle = "Scale of 1 (Strongly Disagree) to 5 (Strongly Agree)") %>%
    tab_source_note(md("Original MTurk Study, conducted 2020 Dec. 11-12 & 2021 Feb. 21,
                        n = 348"))

china.trust.lm <- lm(Q47_1 ~ gender + age + race + education 
                + political_identification + condition, data = numeric_results)

summary(china.trust.lm)

china.biz.policy.lm <- lm(Q49 ~ gender + age + race + education 
                + political_identification + condition, data = numeric_results)

summary(china.biz.policy.lm)


niz.policy.tbl <-  tbl_regression(china.biz.policy.lm, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Tbl. 4: Regression of Treatment Group Against Policy Preference about Chinese 
       Business Integration", 
  subtitle = "Scale of 1 (Ban Chinese companies) to 3 (Undertake friendly cooperation)") %>%
    tab_source_note(md("Original MTurk Study, conducted 2020 Dec. 11-12 & 2021 Feb. 21,
                        n = 348"))


china.fav.ppl.lm <- lm(Q56_4 ~ gender + age + race + education 
                + political_identification + condition, data = numeric_results)

summary(china.fav.ppl.lm)

china.ppl.fav.tbl <-  tbl_regression(china.fav.ppl.lm, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Tbl. 5: Regression of Country-of-Origin Treatment Group Against Favorability Towards Chinese Citizens", 
  subtitle = "Feeling Thermometer of 0 (Coldest) to 100 (Warmest)") %>%
    tab_source_note(md("Original MTurk Study, conducted 2020 Dec. 11-12 & 2021 Feb. 21,
                        n = 348"))


app.usage.lm <- lm(Q36 ~ gender + age + race + education 
                + political_identification + condition, data = numeric_results)

summary(app.usage.lm)

app.keep.lm <- lm(Q35 ~ gender + age + race + education 
                + political_identification + condition, data = numeric_results)

summary(app.keep.lm)

app.keep.lm.tbl <-  tbl_regression(app.keep.lm, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Tbl. 3: Regression of Treatment Group Against Keep/Delete Decision", 
  subtitle = "Binary Scale of 0 (Delete Taply) to 1 (Keep Taply)") %>%
    tab_source_note(md("Original MTurk Study, conducted 2020 Dec. 11-12 & 2021 Feb. 21,
                        n = 348"))

app.country.factor.lm <- lm(Q40 ~ gender + age + race + education 
                + political_identification + condition, data = numeric_results)

summary(app.country.factor.lm)

country.factor.tbl <-  tbl_regression(app.country.factor.lm, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Tbl. 3: Regression of Treatment Group Against Origin Country 
       Factoring into Download Decision", 
  subtitle = "Scale of 1 (Strongly Disagree) to 5 (Strongly Agree)") %>%
    tab_source_note(md("Original MTurk Study, conducted 2020 Dec. 11-12 & 2021 Feb. 21,
                        n = 348"))

app.china.trust.lm <- lm(Q41 ~ gender + age + race + education 
                + political_identification + condition, data = numeric_results)

summary(app.china.trust.lm)

app.china.interaction.lm <- lm(time_spent_using_chinese_apps ~ gender + age + race + education 
                + political_identification + condition, data = numeric_results)

summary(app.china.interaction.lm)

china.tariff.glm <- glm(Q51_1 ~ gender + age + race + education 
                + political_identification + condition, data = numeric_results)

summary(china.tariff.glm)

china.science.glm <- glm(Q51_2 ~ gender + age + race + education 
                + political_identification + condition, data = numeric_results)

summary(china.science.glm)

china.econ.engagement.glm <- glm(Q51_3 ~ gender + age + race + education 
                + political_identification + condition, data = numeric_results)

summary(china.econ.engagement.glm)

econ.engagement.tbl <-  tbl_regression(china.econ.engagement.glm, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Tbl. 4: Logistic Regression of Treatment Group Against Restricting Economic Engagement 
             between American and Chinese Companies", 
  subtitle = "Binary Scale of 0 (Do not restrict economic engagement) to 1 (Restrict economic engagement)") %>%
    tab_source_note(md("Original MTurk Study, conducted 2020 Dec. 11-12 & 2021 Feb. 21,
                        n = 348"))

china.students.glm <- glm(Q51_4 ~ gender + age + race + education 
                + political_identification + condition, data = numeric_results)

summary(china.students.glm)

china.aid.glm <- lm(Q51_5 ~ gender + age + race + education 
                + political_identification + condition, data = numeric_results)

summary(china.aid.glm)

fav.appusage.lm <- lm(Q45_1 ~ gender + age + race + education 
                + political_identification + time_spent_using_chinese_apps, data = numeric_results)

summary(fav.appusage.lm)

fav.appusage.tbl <-  tbl_regression(fav.appusage.lm, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Tbl. 6:  Regression of Time Spent Using Chinese Apps Against Favorability Towards China", 
  subtitle = "Binary Scale of 0 (Oppose) to 1 (Support)") %>%
    tab_source_note(md("Original MTurk Study, conducted 2020 Dec. 11-12 & 2021 Feb. 21,
                        n = 348"))

trust.appusage.lm <- lm(Q37 ~ gender + age + race + education 
                + political_identification + time_spent_using_chinese_apps, data = numeric_results)

summary(trust.appusage.lm)
```


```{r}
mean_china_fav <-
  numeric_results %>%
  group_by(condition) %>%
  summarize(mean_china_fav = mean(Q45_1, na.rm = TRUE),
            sd = sd(Q45_1, na.rm = TRUE),
            n = n()) %>%
  mutate(se = sd / sqrt(n),
         lower.ci = mean_china_fav - qt(1 - (0.05 / 2), n - 1) * se,
         upper.ci = mean_china_fav + qt(1 - (0.05 / 2), n - 1) * se)

china_fav_graph <-
  mean_china_fav %>%
ggplot(aes(x = condition, y = mean_china_fav, fill = condition)) +
  geom_col(position=position_dodge()) +
  geom_errorbar(mapping = aes(x = condition, ymin = lower.ci, ymax = upper.ci),
                width = .2) + 
  ylim(0, 100) +
  scale_fill_discrete(name = "Condition", labels = c("USA Base App", "China Hated App",
                         "China Loved App", "China Base App", "Alt. Base App")) +
  scale_x_discrete(labels=c("USA Base App", "China Hated App",
                         "China Loved App", "China Base App", "Alt. Base App")) +
  labs(title = "Fig. 1: The Effect of App Treatment on Favorability Towards China",
       subtitle = "Feeling Thermometer of 0 (Coldest) to 100 (Warmest)",
       x = "Treatment Group",
       y = "Mean Favorability towards China",
       source = "Original MTurk study, conducted 2020 Dec. 11-12 & 2021 Feb. 21,
                        n = 348") +
  theme_bw()

mean_keep <-
  numeric_results %>%
  group_by(condition) %>%
  summarize(mean_keep = mean(Q35, na.rm = TRUE),
            sd = sd(Q35, na.rm = TRUE),
            n = n()) %>%
  mutate(se = sd / sqrt(n),
         lower.ci = mean_keep - qt(1 - (0.05 / 2), n - 1) * se,
         upper.ci = mean_keep + qt(1 - (0.05 / 2), n - 1) * se)

keep_graph <-
  mean_keep %>%
ggplot(aes(x = condition, y = mean_keep, fill = condition)) +
  geom_col(position=position_dodge()) +
  geom_errorbar(mapping = aes(x = condition, ymin = lower.ci, ymax = upper.ci),
                width = .2) + 
  scale_fill_discrete(name = "Condition", labels = c("USA Base App", "China Hated App",
                         "China Loved App", "China Base App", "Alt. Base App")) +
  scale_x_discrete(labels=c("USA Base App", "China Hated App",
                         "China Loved App", "China Base App", "Alt. Base App")) +
  labs(title = "Fig. 2: The Effect of App Treatment on Keep/Delete Decision",
       subtitle = "Scale of 0 (Delete Taply) to 1 (Keep Taply)",
       x = "Treatment Group",
       y = "Mean Keep/Delete",
       source = "Original MTurk study, conducted 2020 Dec. 11-12 & 2021 Feb. 21,
                        n = 348") +
  theme_bw()

mean_trust <-
  numeric_results %>%
  group_by(condition) %>%
  summarize(mean_trust = mean(Q37, na.rm = TRUE),
            sd = sd(Q37, na.rm = TRUE),
            n = n()) %>%
  mutate(se = sd / sqrt(n),
         lower.ci = mean_trust - qt(1 - (0.05 / 2), n - 1) * se,
         upper.ci = mean_trust + qt(1 - (0.05 / 2), n - 1) * se)

trust_graph <-
mean_trust %>%
ggplot(aes(x = condition, y = mean_trust, fill = condition)) +
  geom_col(position=position_dodge()) +
  geom_errorbar(mapping = aes(x = condition, ymin = lower.ci, ymax = upper.ci),
                width = .2) + 
  ylim(0, 5) +
  scale_fill_discrete(name = "Condition", labels = c("USA Base App", "China Hated App",
                         "China Loved App", "China Base App", "Alt. Base App")) +
  scale_x_discrete(labels=c("USA Base App", "China Hated App",
                         "China Loved App", "China Base App", "Alt. Base App")) +
  labs(title = "Fig. 2: The Effect of App Treatment on Perceived Company Trust",
       subtitle = "Scale of 1 (Strongly Disagree) to 5 (Strongly Agree)",
       x = "Treatment Group",
       y = "Mean Company Trust",
       source = "Original MTurk study, conducted 2020 Dec. 11-12 & 2021 Feb. 21,
                        n = 348") +
  theme_bw()

mean_china_biz_policy <-
  numeric_results %>%
  group_by(condition) %>%
  summarize(mean_policy = mean(Q51_3, na.rm = TRUE),
            sd = sd(Q51_3, na.rm = TRUE),
            n = n()) %>%
  mutate(se = sd / sqrt(n),
         lower.ci = mean_policy - qt(1 - (0.05 / 2), n - 1) * se,
         upper.ci = mean_policy + qt(1 - (0.05 / 2), n - 1) * se)

china_biz_policy_graph <-
mean_china_biz_policy %>%
ggplot(aes(x = condition, y = mean_policy, fill = condition)) +
  geom_col(position=position_dodge()) +
  geom_errorbar(mapping = aes(x = condition, ymin = lower.ci, ymax = upper.ci),
                width = .2) + 
  ylim(0, 1) +
  scale_fill_discrete(name = "Condition", labels = c("USA Base App", "China Hated App",
                         "China Loved App", "China Base App", "Alt. Base App")) +
  scale_x_discrete(labels=c("USA Base App", "China Hated App",
                         "China Loved App", "China Base App", "Alt. Base App")) +
  labs(title = "Fig. 4: The Effect of App Treatment on Attitudes about U.S.-China Business 
       Interaction",
       subtitle = "Binary Scale of 0 (Do not restrict economic engagement) to 1 (Restrict economic engagement)",
       x = "Treatment Group",
       y = "Mean Attitude",
       source = "Original MTurk study, conducted 2020 Dec. 11-12 & 2021 Feb. 21,
                        n = 348") +
  theme_bw()

mean_keep_decision <-
  numeric_results %>%
  group_by(condition) %>%
  summarize(mean_policy = mean(Q35, na.rm = TRUE),
            sd = sd(Q35, na.rm = TRUE),
            n = n()) %>%
  mutate(se = sd / sqrt(n),
         lower.ci = mean_policy - qt(1 - (0.05 / 2), n - 1) * se,
         upper.ci = mean_policy + qt(1 - (0.05 / 2), n - 1) * se)

mean_china_threat_policy <-
mean_keep_decision %>%
ggplot(aes(x = condition, y = mean_policy, fill = condition)) +
  geom_col(position=position_dodge()) +
  geom_errorbar(mapping = aes(x = condition, ymin = lower.ci, ymax = upper.ci),
                width = .2) + 
  ylim(0, 1) +
  scale_fill_discrete(name = "Condition", labels = c("USA Base App", "China Hated App",
                         "China Loved App", "China Base App", "Alt. Base App")) +
  scale_x_discrete(labels=c("USA Base App", "China Hated App",
                         "China Loved App", "China Base App", "Alt. Base App")) +
  labs(title = "Fig. 3: The Effect of App Treatment on Keep/Delete Decisions",
       subtitle = "Scale of 0 (Delete Taply) to 1 (Keep Taply)",
       x = "Treatment Group",
       y = "Mean Keep/Delete",
       source = "Original MTurk study, conducted 2020 Dec. 11-12 & 2021 Feb. 21,
                        n = 348") +
  theme_bw()


mean_china_ppl_fav <-
  numeric_results %>%
  group_by(condition) %>%
  summarize(mean_china_ppl_fav = mean(Q56_4, na.rm = TRUE),
            sd = sd(Q56_4, na.rm = TRUE),
            n = n()) %>%
  mutate(se = sd / sqrt(n),
         lower.ci = mean_china_ppl_fav - qt(1 - (0.05 / 2), n - 1) * se,
         upper.ci = mean_china_ppl_fav + qt(1 - (0.05 / 2), n - 1) * se)

china_ppl_fav_graph <-
  mean_china_ppl_fav %>%
ggplot(aes(x = condition, y = mean_china_ppl_fav, fill = condition)) +
  geom_col(position=position_dodge()) +
  geom_errorbar(mapping = aes(x = condition, ymin = lower.ci, ymax = upper.ci),
                width = .2) + 
  ylim(0, 100) +
  scale_fill_discrete(name = "Condition", labels = c("USA Base App", "China Hated App",
                         "China Loved App", "China Base App", "Alt. Base App")) +
  scale_x_discrete(labels=c("USA Base App", "China Hated App",
                         "China Loved App", "China Base App", "Alt. Base App")) +
  labs(title = "Fig. 5: The Effect of App Treatment on Favorability Towards Chinese Citizens",
       subtitle = "Feeling Thermometer of 0 (Coldest) to 100 (Warmest)",
       x = "Treatment Group",
       y = "Mean Favorability towards Chinese Citizens",
       source = "Original MTurk study, conducted 2020 Dec. 11-12 & 2021 Feb. 21,
                        n = 348") +
  theme_bw()



mean_origin_country <-
  numeric_results %>%
  group_by(condition) %>%
  summarize(mean_origin_country = mean(Q40, na.rm = TRUE),
            sd = sd(Q40, na.rm = TRUE),
            n = n()) %>%
  mutate(se = sd / sqrt(n),
         lower.ci = mean_origin_country - qt(1 - (0.05 / 2), n - 1) * se,
         upper.ci = mean_origin_country + qt(1 - (0.05 / 2), n - 1) * se)

origin_country_graph <-
  mean_origin_country %>%
ggplot(aes(x = condition, y = mean_origin_country, fill = condition)) +
  geom_col(position=position_dodge()) +
  geom_errorbar(mapping = aes(x = condition, ymin = lower.ci, ymax = upper.ci),
                width = .2) + 
  ylim(0, 5) +
  scale_fill_discrete(name = "Condition", labels = c("USA Base App", "China Hated App",
                         "China Loved App", "China Base App", "Alt. Base App")) +
  scale_x_discrete(labels=c("USA Base App", "China Hated App",
                         "China Loved App", "China Base App", "Alt. Base App")) +
  labs(title = "The Effect of App Treatment on Whether Origin Country Factored into Download Decision",
       subtitle = "Scale of 1 (Strongly Disagree) to 5 (Strongly Agree)",
       x = "Treatment Group",
       y = "Mean Attitude about Origin Country",
       source = "Original MTurk study, conducted 2020 Dec. 11-12 & 2021 Feb. 21,
                        n = 348") +
  theme_bw()

```

```{r}
fav_regression_graph <-
  numeric_results %>%
   ggplot(aes(x = condition_scale, y = as.numeric(Q45_1), color = condition_scale)) +
   geom_point(alpha = .3) +
   geom_smooth(method = "loess", formula = y~x) +
  scale_color_continuous(name = "Condition", limits = c(1,5), labels = c("USA Base App", "China Base App",
                         "China Hated App", "China Loved App", "Alt. Base App")) +
  scale_x_continuous(labels=c("USA Base App", "China Base App",
                         "China Hated App", "China Loved App", "Alt. Base App")) +
  labs(title = "LOEES Regression of Treatment Group Against Favorability Towards China",
       subtitle = "favorability ~ treatment, Feeling Thermometer of 0 (Coldest) to 100 (Warmest)",
       x = "Treatment Group",
       y = "Favorability",
       source = "Original mTurk study, conducted 2020 Dec. 11-12 & 2021 Feb. 21,
                        n = 348") +
  theme_bw()


labels <- c(1 == "Democrat", 2 == "Republican", 3 == "Independent")

china_ppl_fav_graph_party <-
  numeric_results %>%
  filter(political_identification %in% c(1,2,3)) %>%
  group_by(political_identification) %>%
ggplot(aes(y = Q45_1, fill = condition)) +
  geom_boxplot() +
  facet_grid(.~political_identification,
             labeller = labeller(labels)) +
  scale_fill_discrete(name = "Treatment") +
          labs(title = "Effect of Treatment Assignment and Political Identification
               on American Attitudes Towards China ",
               subtitle = "0 = Very Cold; 50 = Not particuarly Warm or Cold;
       100 = Very Warm",
               x = "",
               y = "American Attitudes") +
  theme(axis.text.x=element_blank()) +
          theme_bw()

trust_graph_party <-
  numeric_results %>%
  filter(political_identification %in% c(1,2,3)) %>%
  group_by(condition) %>%
ggplot(aes(y = Q37, color = condition)) +
  geom_boxplot() +
  facet_grid(.~political_identification,
             labeller = labeller(labels)) +
  scale_fill_discrete(name = "Treatment") +
          labs(title = "Effect of Treatment Assignment and Political Identification
               on Trust Assigned to Taply ",
               subtitle = "Scale of 1 (Strongly Disagree) to 5 (Strongly Agree)",
               x = "",
               y = "Assigned Trust") +
  theme(axis.text.x=element_blank()) +
          theme_bw()

trust_regression_graph <-
   numeric_results %>%
   ggplot(aes(x = condition_scale, y = as.numeric(Q37), color = condition_scale)) +
   geom_point(alpha = .3) +
   geom_smooth(method = "loess", formula = y~x) +
  scale_color_continuous(name = "Condition", limits = c(1,5), labels = c("USA Base App", "China Base App",
                         "China Hated App", "China Loved App", "Alt. Base App")) +
  scale_x_continuous(labels=c("USA Base App", "China Base App",
                         "China Hated App", "China Loved App", "Alt. Base App")) +
  labs(title = "LOEES Regression of Treatment Group Against Trust Assigned to Taply",
       subtitle = "trust ~ treatment, Scale of 1 (Strongly Disagree) to 5 (Strongly Agree)",
       x = "Treatment Group",
       y = "Assigned Trust",
       source = "Original mTurk study, conducted 2020 Dec. 11-12 & 2021 Feb. 21,
                        n = 348") +
  theme_bw()

china_biz_regression_graph <-
   numeric_results %>%
   ggplot(aes(x = condition_scale, y = as.numeric(Q49), color = condition_scale)) +
   geom_point(alpha = .3) +
   geom_smooth(method = "loess", formula = y~x) +
  scale_color_continuous(name = "Condition", limits = c(1,5), labels = c("USA Base App", "China Base App",
                         "China Hated App", "China Loved App", "Alt. Base App")) +
  scale_x_continuous(labels=c("USA Base App", "China Base App",
                         "China Hated App", "China Loved App", "Alt. Base App")) +
  labs(title = "LOEES Regression of Treatment Group Against Policy Preference about Chinese 
       Business Integration",
       subtitle = "business_policy ~ treatment, 
       Scale of 1 (Ban Chinese companies) to 3 (Undertake friendly cooperation)",
       x = "Treatment Group",
       y = "Policy Preference",
       source = "Original mTurk study, conducted 2020 Dec. 11-12 & 2021 Feb. 21,
                        n = 348") +
  theme_bw()

china_ppl_fav_regression_graph <-
   numeric_results %>%
   ggplot(aes(x = condition_scale, y = as.numeric(Q56_4), color = condition_scale)) +
   geom_point(alpha = .3) +
   geom_smooth(method = "loess", formula = y~x) +
  scale_color_continuous(name = "Condition", limits = c(1,5), labels = c("USA Base App", "China Base App",
                         "China Hated App", "China Loved App", "Alt. Base App")) +
  scale_x_continuous(labels=c("USA Base App", "China Base App",
                         "China Hated App", "China Loved App", "Alt. Base App")) +
  labs(title = "LOEES Regression of Treatment Group Against Favorability of Chinese Citizens",
       subtitle = "people_favorability ~ treatment, Feeling Thermometer of 0 (Coldest) to 100 (Warmest)",
       x = "Treatment Group",
       y = "Favorability",
       source = "Original mTurk study, conducted 2020 Dec. 11-12 & 2021 Feb. 21,
                        n = 348") +
  theme_bw()

keep_regression_graph <-
   numeric_results %>%
   ggplot(aes(x = condition_scale, y = as.numeric(Q35), color = condition_scale)) +
   geom_point(alpha = .3) +
   geom_smooth(method = "loess", formula = y~x) +
  scale_color_continuous(name = "Condition", limits = c(1,5), labels = c("USA Base App", "China Base App",
                         "China Hated App", "China Loved App", "Alt. Base App")) +
  scale_x_continuous(labels=c("USA Base App", "China Base App",
                         "China Hated App", "China Loved App", "Alt. Base App")) +
  labs(title = "LOEES Regression of Treatment Group Against Keep/Delete Decision",
       subtitle = "keep/delete ~ treatment, Scale of 1 (Strongly Disagree) to 5 (Strongly Agree)",
       x = "Treatment Group",
       y = "Attitude of Origin Country Factoring into Download",
       source = "Original mTurk study, conducted 2020 Dec. 11-12 & 2021 Feb. 21,
                        n = 348") +
  theme_bw()
```

